///************************************************
/// Generated by: ninhvh
/// Date: 26/06/2012 11:20:43
/// Goal: Create User Service Class for TBL_GD_THANH_TOAN
///************************************************
/// <summary>
/// Create User Service Class for TBL_GD_THANH_TOAN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_TBL_GD_THANH_TOAN : US_Object
{
	private const string c_TableName = "TBL_GD_THANH_TOAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strSO_PHIEU_THANH_TOAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_PHIEU_THANH_TOAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_PHIEU_THANH_TOAN"] = value;
		}
	}

	public bool IsSO_PHIEU_THANH_TOANNull() 
	{
		return pm_objDR.IsNull("SO_PHIEU_THANH_TOAN");
	}

	public void SetSO_PHIEU_THANH_TOANNull() {
		pm_objDR["SO_PHIEU_THANH_TOAN"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_THANH_TOAN
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_THANH_TOAN", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_THANH_TOAN"] = value;
		}
	}

	public bool IsNGAY_THANH_TOANNull()
	{
		return pm_objDR.IsNull("NGAY_THANH_TOAN");
	}

	public void SetNGAY_THANH_TOANNull()
	{
		pm_objDR["NGAY_THANH_TOAN"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_QUANLY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_QUANLY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_QUANLY"] = value;
		}
	}

	public bool IsID_DON_VI_QUANLYNull()	{
		return pm_objDR.IsNull("ID_DON_VI_QUANLY");
	}

	public void SetID_DON_VI_QUANLYNull() {
		pm_objDR["ID_DON_VI_QUANLY"] = System.Convert.DBNull;
	}

	public decimal dcID_GIANG_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_GIANG_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_GIANG_VIEN"] = value;
		}
	}

	public bool IsID_GIANG_VIENNull()	{
		return pm_objDR.IsNull("ID_GIANG_VIEN");
	}

	public void SetID_GIANG_VIENNull() {
		pm_objDR["ID_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strTEN_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_GIANG_VIEN"] = value;
		}
	}

	public bool IsTEN_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("TEN_GIANG_VIEN");
	}

	public void SetTEN_GIANG_VIENNull() {
		pm_objDR["TEN_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strSO_TAI_KHOAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "SO_TAI_KHOAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["SO_TAI_KHOAN"] = value;
		}
	}

	public bool IsSO_TAI_KHOANNull() 
	{
		return pm_objDR.IsNull("SO_TAI_KHOAN");
	}

	public void SetSO_TAI_KHOANNull() {
		pm_objDR["SO_TAI_KHOAN"] = System.Convert.DBNull;
	}

	public string strTEN_NGAN_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGAN_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGAN_HANG"] = value;
		}
	}

	public bool IsTEN_NGAN_HANGNull() 
	{
		return pm_objDR.IsNull("TEN_NGAN_HANG");
	}

	public void SetTEN_NGAN_HANGNull() {
		pm_objDR["TEN_NGAN_HANG"] = System.Convert.DBNull;
	}

	public string strMA_SO_THUE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_SO_THUE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_SO_THUE"] = value;
		}
	}

	public bool IsMA_SO_THUENull() 
	{
		return pm_objDR.IsNull("MA_SO_THUE");
	}

	public void SetMA_SO_THUENull() {
		pm_objDR["MA_SO_THUE"] = System.Convert.DBNull;
	}

	public decimal dcTONG_TIEN_THANH_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "TONG_TIEN_THANH_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["TONG_TIEN_THANH_TOAN"] = value;
		}
	}

	public bool IsTONG_TIEN_THANH_TOANNull()	{
		return pm_objDR.IsNull("TONG_TIEN_THANH_TOAN");
	}

	public void SetTONG_TIEN_THANH_TOANNull() {
		pm_objDR["TONG_TIEN_THANH_TOAN"] = System.Convert.DBNull;
	}

	public decimal dcCON_PHAI_THANH_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "CON_PHAI_THANH_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["CON_PHAI_THANH_TOAN"] = value;
		}
	}

	public bool IsCON_PHAI_THANH_TOANNull()	{
		return pm_objDR.IsNull("CON_PHAI_THANH_TOAN");
	}

	public void SetCON_PHAI_THANH_TOANNull() {
		pm_objDR["CON_PHAI_THANH_TOAN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_TBL_GD_THANH_TOAN() 
	{
		pm_objDS = new DS_TBL_GD_THANH_TOAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_TBL_GD_THANH_TOAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_TBL_GD_THANH_TOAN(decimal i_dbID) 
	{
		pm_objDS = new DS_TBL_GD_THANH_TOAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
