///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'GD_HOP_DONG_NOI_DUNG_TT'
// Generated by LLBLGen v1.21.2003.712 Final on: Monday, October 03, 2011, 10:53:14 AM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace TRMLLBL
{
	/// <summary>
	/// Purpose: Data Access class for the table 'GD_HOP_DONG_NOI_DUNG_TT'.
	/// </summary>
	public class GD_HOP_DONG_NOI_DUNG_TT : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlDecimal		_sO_LUONG_HE_SO, _dON_GIA_HD, _iD_NOI_DUNG_TT, _iD_NOI_DUNG_TTOld, _iD, _iD_HOP_DONG_KHUNG, _iD_HOP_DONG_KHUNGOld;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public GD_HOP_DONG_NOI_DUNG_TT()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_HOP_DONG_KHUNG</LI>
		///		 <LI>ID_NOI_DUNG_TT</LI>
		///		 <LI>SO_LUONG_HE_SO</LI>
		///		 <LI>DON_GIA_HD</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_HOP_DONG_KHUNG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_HOP_DONG_KHUNG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_NOI_DUNG_TT", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_NOI_DUNG_TT));
				cmdToExecute.Parameters.Add(new SqlParameter("@SO_LUONG_HE_SO", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _sO_LUONG_HE_SO));
				cmdToExecute.Parameters.Add(new SqlParameter("@DON_GIA_HD", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _dON_GIA_HD));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Output, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_iD = (Decimal)cmdToExecute.Parameters["@ID"].Value;
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::Insert::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		///		 <LI>ID_HOP_DONG_KHUNG</LI>
		///		 <LI>ID_NOI_DUNG_TT</LI>
		///		 <LI>SO_LUONG_HE_SO</LI>
		///		 <LI>DON_GIA_HD</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_Update]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_HOP_DONG_KHUNG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_HOP_DONG_KHUNG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_NOI_DUNG_TT", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_NOI_DUNG_TT));
				cmdToExecute.Parameters.Add(new SqlParameter("@SO_LUONG_HE_SO", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _sO_LUONG_HE_SO));
				cmdToExecute.Parameters.Add(new SqlParameter("@DON_GIA_HD", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _dON_GIA_HD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::Update::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method for updating one or more rows using the Foreign Key 'ID_HOP_DONG_KHUNG.
		/// This method will Update one or more existing rows in the database. It will reset the field 'ID_HOP_DONG_KHUNG' in
		/// all rows which have as value for this field the value as set in property 'ID_HOP_DONG_KHUNGOld' to 
		/// the value as set in property 'ID_HOP_DONG_KHUNG'.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_HOP_DONG_KHUNG</LI>
		///		 <LI>ID_HOP_DONG_KHUNGOld</LI>
		/// </UL>
		/// </remarks>
		public bool UpdateAllWID_HOP_DONG_KHUNGLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_UpdateAllWID_HOP_DONG_KHUNGLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_HOP_DONG_KHUNG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_HOP_DONG_KHUNG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_HOP_DONG_KHUNGOld", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_HOP_DONG_KHUNGOld));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::UpdateAllWID_HOP_DONG_KHUNGLogic::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method for updating one or more rows using the Foreign Key 'ID_NOI_DUNG_TT.
		/// This method will Update one or more existing rows in the database. It will reset the field 'ID_NOI_DUNG_TT' in
		/// all rows which have as value for this field the value as set in property 'ID_NOI_DUNG_TTOld' to 
		/// the value as set in property 'ID_NOI_DUNG_TT'.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_NOI_DUNG_TT</LI>
		///		 <LI>ID_NOI_DUNG_TTOld</LI>
		/// </UL>
		/// </remarks>
		public bool UpdateAllWID_NOI_DUNG_TTLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_UpdateAllWID_NOI_DUNG_TTLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_NOI_DUNG_TT", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_NOI_DUNG_TT));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_NOI_DUNG_TTOld", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_NOI_DUNG_TTOld));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::UpdateAllWID_NOI_DUNG_TTLogic::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_Delete]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::Delete::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method for a foreign key. This method will Delete one or more rows from the database, based on the Foreign Key 'ID_HOP_DONG_KHUNG'
		/// </summary>
		/// <returns>True if succeeded, false otherwise. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_HOP_DONG_KHUNG</LI>
		/// </UL>
		/// </remarks>
		public bool DeleteAllWID_HOP_DONG_KHUNGLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_DeleteAllWID_HOP_DONG_KHUNGLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_HOP_DONG_KHUNG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_HOP_DONG_KHUNG));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::DeleteAllWID_HOP_DONG_KHUNGLogic::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method for a foreign key. This method will Delete one or more rows from the database, based on the Foreign Key 'ID_NOI_DUNG_TT'
		/// </summary>
		/// <returns>True if succeeded, false otherwise. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID_NOI_DUNG_TT</LI>
		/// </UL>
		/// </remarks>
		public bool DeleteAllWID_NOI_DUNG_TTLogic()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_GD_HOP_DONG_NOI_DUNG_TT_DeleteAllWID_NOI_DUNG_TTLogic]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_NOI_DUNG_TT", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_NOI_DUNG_TT));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("GD_HOP_DONG_NOI_DUNG_TT::DeleteAllWID_NOI_DUNG_TTLogic::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlDecimal ID
		{
			get
			{
				return _iD;
			}
			set
			{
				SqlDecimal iDTmp = (SqlDecimal)value;
				if(iDTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID", "ID can't be NULL");
				}
				_iD = value;
			}
		}


		public SqlDecimal ID_HOP_DONG_KHUNG
		{
			get
			{
				return _iD_HOP_DONG_KHUNG;
			}
			set
			{
				SqlDecimal iD_HOP_DONG_KHUNGTmp = (SqlDecimal)value;
				if(iD_HOP_DONG_KHUNGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_HOP_DONG_KHUNG", "ID_HOP_DONG_KHUNG can't be NULL");
				}
				_iD_HOP_DONG_KHUNG = value;
			}
		}
		public SqlDecimal ID_HOP_DONG_KHUNGOld
		{
			get
			{
				return _iD_HOP_DONG_KHUNGOld;
			}
			set
			{
				SqlDecimal iD_HOP_DONG_KHUNGOldTmp = (SqlDecimal)value;
				if(iD_HOP_DONG_KHUNGOldTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_HOP_DONG_KHUNGOld", "ID_HOP_DONG_KHUNGOld can't be NULL");
				}
				_iD_HOP_DONG_KHUNGOld = value;
			}
		}


		public SqlDecimal ID_NOI_DUNG_TT
		{
			get
			{
				return _iD_NOI_DUNG_TT;
			}
			set
			{
				SqlDecimal iD_NOI_DUNG_TTTmp = (SqlDecimal)value;
				if(iD_NOI_DUNG_TTTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_NOI_DUNG_TT", "ID_NOI_DUNG_TT can't be NULL");
				}
				_iD_NOI_DUNG_TT = value;
			}
		}
		public SqlDecimal ID_NOI_DUNG_TTOld
		{
			get
			{
				return _iD_NOI_DUNG_TTOld;
			}
			set
			{
				SqlDecimal iD_NOI_DUNG_TTOldTmp = (SqlDecimal)value;
				if(iD_NOI_DUNG_TTOldTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_NOI_DUNG_TTOld", "ID_NOI_DUNG_TTOld can't be NULL");
				}
				_iD_NOI_DUNG_TTOld = value;
			}
		}


		public SqlDecimal SO_LUONG_HE_SO
		{
			get
			{
				return _sO_LUONG_HE_SO;
			}
			set
			{
				SqlDecimal sO_LUONG_HE_SOTmp = (SqlDecimal)value;
				if(sO_LUONG_HE_SOTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("SO_LUONG_HE_SO", "SO_LUONG_HE_SO can't be NULL");
				}
				_sO_LUONG_HE_SO = value;
			}
		}


		public SqlDecimal DON_GIA_HD
		{
			get
			{
				return _dON_GIA_HD;
			}
			set
			{
				SqlDecimal dON_GIA_HDTmp = (SqlDecimal)value;
				if(dON_GIA_HDTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("DON_GIA_HD", "DON_GIA_HD can't be NULL");
				}
				_dON_GIA_HD = value;
			}
		}
		#endregion
	}
}
