///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the view 'V_DM_HOP_DONG_KHUNG'
// Generated by LLBLGen v1.21.2003.712 Final on: Wednesday, September 28, 2011, 6:17:27 PM
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace TRMLLBL
{
	/// <summary>
	/// Purpose: Data Access class for the view 'V_DM_HOP_DONG_KHUNG'.
	/// </summary>
	public class V_DM_HOP_DONG_KHUNG : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlDateTime		_nGAY_KET_THUC_DU_KIEN, _nGAY_KY, _nGAY_HIEU_LUC;
			private SqlDecimal		_iD_MON1, _tHUE_SUAT, _iD_TRANG_THAI_HOP_DONG, _iD_DON_VI_THANH_TOAN, _iD_MON2, _iD_MON4, _iD_MON5, _iD_MON6, _iD_MON3, _iD_LOAI_HOP_DONG, _gIA_TRI_HOP_DONG, _iD, _iD_DON_VI_QUAN_LY, _iD_GIANG_VIEN;
			private SqlString		_hOC_LIEU_YN, _vAN_HANH_YN, _fITH_MON, _sIXTH_MON, _gHI_CHU2, _gHI_CHU3, _gHI_CHU4, _cO_SO_HD_YN, _mA_PO_PHU_TRACH, _sO_HOP_DONG, _lOAI_HOP_DONG, _fIRST_MON, _dON_VI_THANH_TOAN, _dON_VI_QUAN_LY, _tRANG_THAI_HOP_DONG, _gHI_CHU, _fOURTH_MON, _tHIR_MON, _sEC_MON, _gIANG_VIEN;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public V_DM_HOP_DONG_KHUNG()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>SO_HOP_DONG</LI>
		///		 <LI>ID_GIANG_VIEN</LI>
		///		 <LI>GIANG_VIEN. May be SqlString.Null</LI>
		///		 <LI>NGAY_KY</LI>
		///		 <LI>NGAY_HIEU_LUC. May be SqlDateTime.Null</LI>
		///		 <LI>NGAY_KET_THUC_DU_KIEN. May be SqlDateTime.Null</LI>
		///		 <LI>GIA_TRI_HOP_DONG. May be SqlDecimal.Null</LI>
		///		 <LI>ID_LOAI_HOP_DONG</LI>
		///		 <LI>LOAI_HOP_DONG. May be SqlString.Null</LI>
		///		 <LI>ID_DON_VI_QUAN_LY</LI>
		///		 <LI>DON_VI_QUAN_LY. May be SqlString.Null</LI>
		///		 <LI>GHI_CHU. May be SqlString.Null</LI>
		///		 <LI>ID_TRANG_THAI_HOP_DONG</LI>
		///		 <LI>TRANG_THAI_HOP_DONG. May be SqlString.Null</LI>
		///		 <LI>ID_DON_VI_THANH_TOAN</LI>
		///		 <LI>DON_VI_THANH_TOAN. May be SqlString.Null</LI>
		///		 <LI>THUE_SUAT. May be SqlDecimal.Null</LI>
		///		 <LI>ID_MON1</LI>
		///		 <LI>FIRST_MON. May be SqlString.Null</LI>
		///		 <LI>ID_MON2. May be SqlDecimal.Null</LI>
		///		 <LI>SEC_MON. May be SqlString.Null</LI>
		///		 <LI>ID_MON3. May be SqlDecimal.Null</LI>
		///		 <LI>THIR_MON. May be SqlString.Null</LI>
		///		 <LI>ID_MON4. May be SqlDecimal.Null</LI>
		///		 <LI>FOURTH_MON. May be SqlString.Null</LI>
		///		 <LI>ID_MON5. May be SqlDecimal.Null</LI>
		///		 <LI>FITH_MON. May be SqlString.Null</LI>
		///		 <LI>ID_MON6. May be SqlDecimal.Null</LI>
		///		 <LI>SIXTH_MON. May be SqlString.Null</LI>
		///		 <LI>HOC_LIEU_YN</LI>
		///		 <LI>VAN_HANH_YN</LI>
		///		 <LI>MA_PO_PHU_TRACH. May be SqlString.Null</LI>
		///		 <LI>GHI_CHU2. May be SqlString.Null</LI>
		///		 <LI>GHI_CHU3. May be SqlString.Null</LI>
		///		 <LI>GHI_CHU4. May be SqlString.Null</LI>
		///		 <LI>CO_SO_HD_YN</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_V_DM_HOP_DONG_KHUNG_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@SO_HOP_DONG", SqlDbType.NVarChar, 35, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _sO_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_GIANG_VIEN", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_GIANG_VIEN));
				cmdToExecute.Parameters.Add(new SqlParameter("@GIANG_VIEN", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gIANG_VIEN));
				cmdToExecute.Parameters.Add(new SqlParameter("@NGAY_KY", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nGAY_KY));
				cmdToExecute.Parameters.Add(new SqlParameter("@NGAY_HIEU_LUC", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nGAY_HIEU_LUC));
				cmdToExecute.Parameters.Add(new SqlParameter("@NGAY_KET_THUC_DU_KIEN", SqlDbType.DateTime, 8, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _nGAY_KET_THUC_DU_KIEN));
				cmdToExecute.Parameters.Add(new SqlParameter("@GIA_TRI_HOP_DONG", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _gIA_TRI_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_LOAI_HOP_DONG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_LOAI_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@LOAI_HOP_DONG", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _lOAI_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_DON_VI_QUAN_LY", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_DON_VI_QUAN_LY));
				cmdToExecute.Parameters.Add(new SqlParameter("@DON_VI_QUAN_LY", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _dON_VI_QUAN_LY));
				cmdToExecute.Parameters.Add(new SqlParameter("@GHI_CHU", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gHI_CHU));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_TRANG_THAI_HOP_DONG", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_TRANG_THAI_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@TRANG_THAI_HOP_DONG", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _tRANG_THAI_HOP_DONG));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_DON_VI_THANH_TOAN", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_DON_VI_THANH_TOAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@DON_VI_THANH_TOAN", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _dON_VI_THANH_TOAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@THUE_SUAT", SqlDbType.Decimal, 13, ParameterDirection.Input, false, 21, 3, "", DataRowVersion.Proposed, _tHUE_SUAT));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON1", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON1));
				cmdToExecute.Parameters.Add(new SqlParameter("@FIRST_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _fIRST_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON2", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON2));
				cmdToExecute.Parameters.Add(new SqlParameter("@SEC_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _sEC_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON3", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON3));
				cmdToExecute.Parameters.Add(new SqlParameter("@THIR_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _tHIR_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON4", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON4));
				cmdToExecute.Parameters.Add(new SqlParameter("@FOURTH_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _fOURTH_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON5", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON5));
				cmdToExecute.Parameters.Add(new SqlParameter("@FITH_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _fITH_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID_MON6", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD_MON6));
				cmdToExecute.Parameters.Add(new SqlParameter("@SIXTH_MON", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _sIXTH_MON));
				cmdToExecute.Parameters.Add(new SqlParameter("@HOC_LIEU_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _hOC_LIEU_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@VAN_HANH_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _vAN_HANH_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@MA_PO_PHU_TRACH", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _mA_PO_PHU_TRACH));
				cmdToExecute.Parameters.Add(new SqlParameter("@GHI_CHU2", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gHI_CHU2));
				cmdToExecute.Parameters.Add(new SqlParameter("@GHI_CHU3", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gHI_CHU3));
				cmdToExecute.Parameters.Add(new SqlParameter("@GHI_CHU4", SqlDbType.NVarChar, 250, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _gHI_CHU4));
				cmdToExecute.Parameters.Add(new SqlParameter("@CO_SO_HD_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _cO_SO_HD_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Output, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_iD = (Decimal)cmdToExecute.Parameters["@ID"].Value;
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("V_DM_HOP_DONG_KHUNG::Insert::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlDecimal ID
		{
			get
			{
				return _iD;
			}
			set
			{
				SqlDecimal iDTmp = (SqlDecimal)value;
				if(iDTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID", "ID can't be NULL");
				}
				_iD = value;
			}
		}


		public SqlString SO_HOP_DONG
		{
			get
			{
				return _sO_HOP_DONG;
			}
			set
			{
				SqlString sO_HOP_DONGTmp = (SqlString)value;
				if(sO_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("SO_HOP_DONG", "SO_HOP_DONG can't be NULL");
				}
				_sO_HOP_DONG = value;
			}
		}


		public SqlDecimal ID_GIANG_VIEN
		{
			get
			{
				return _iD_GIANG_VIEN;
			}
			set
			{
				SqlDecimal iD_GIANG_VIENTmp = (SqlDecimal)value;
				if(iD_GIANG_VIENTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_GIANG_VIEN", "ID_GIANG_VIEN can't be NULL");
				}
				_iD_GIANG_VIEN = value;
			}
		}


		public SqlString GIANG_VIEN
		{
			get
			{
				return _gIANG_VIEN;
			}
			set
			{
				SqlString gIANG_VIENTmp = (SqlString)value;
				if(gIANG_VIENTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GIANG_VIEN", "GIANG_VIEN can't be NULL");
				}
				_gIANG_VIEN = value;
			}
		}


		public SqlDateTime NGAY_KY
		{
			get
			{
				return _nGAY_KY;
			}
			set
			{
				SqlDateTime nGAY_KYTmp = (SqlDateTime)value;
				if(nGAY_KYTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NGAY_KY", "NGAY_KY can't be NULL");
				}
				_nGAY_KY = value;
			}
		}


		public SqlDateTime NGAY_HIEU_LUC
		{
			get
			{
				return _nGAY_HIEU_LUC;
			}
			set
			{
				SqlDateTime nGAY_HIEU_LUCTmp = (SqlDateTime)value;
				if(nGAY_HIEU_LUCTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NGAY_HIEU_LUC", "NGAY_HIEU_LUC can't be NULL");
				}
				_nGAY_HIEU_LUC = value;
			}
		}


		public SqlDateTime NGAY_KET_THUC_DU_KIEN
		{
			get
			{
				return _nGAY_KET_THUC_DU_KIEN;
			}
			set
			{
				SqlDateTime nGAY_KET_THUC_DU_KIENTmp = (SqlDateTime)value;
				if(nGAY_KET_THUC_DU_KIENTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("NGAY_KET_THUC_DU_KIEN", "NGAY_KET_THUC_DU_KIEN can't be NULL");
				}
				_nGAY_KET_THUC_DU_KIEN = value;
			}
		}


		public SqlDecimal GIA_TRI_HOP_DONG
		{
			get
			{
				return _gIA_TRI_HOP_DONG;
			}
			set
			{
				SqlDecimal gIA_TRI_HOP_DONGTmp = (SqlDecimal)value;
				if(gIA_TRI_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GIA_TRI_HOP_DONG", "GIA_TRI_HOP_DONG can't be NULL");
				}
				_gIA_TRI_HOP_DONG = value;
			}
		}


		public SqlDecimal ID_LOAI_HOP_DONG
		{
			get
			{
				return _iD_LOAI_HOP_DONG;
			}
			set
			{
				SqlDecimal iD_LOAI_HOP_DONGTmp = (SqlDecimal)value;
				if(iD_LOAI_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_LOAI_HOP_DONG", "ID_LOAI_HOP_DONG can't be NULL");
				}
				_iD_LOAI_HOP_DONG = value;
			}
		}


		public SqlString LOAI_HOP_DONG
		{
			get
			{
				return _lOAI_HOP_DONG;
			}
			set
			{
				SqlString lOAI_HOP_DONGTmp = (SqlString)value;
				if(lOAI_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("LOAI_HOP_DONG", "LOAI_HOP_DONG can't be NULL");
				}
				_lOAI_HOP_DONG = value;
			}
		}


		public SqlDecimal ID_DON_VI_QUAN_LY
		{
			get
			{
				return _iD_DON_VI_QUAN_LY;
			}
			set
			{
				SqlDecimal iD_DON_VI_QUAN_LYTmp = (SqlDecimal)value;
				if(iD_DON_VI_QUAN_LYTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_DON_VI_QUAN_LY", "ID_DON_VI_QUAN_LY can't be NULL");
				}
				_iD_DON_VI_QUAN_LY = value;
			}
		}


		public SqlString DON_VI_QUAN_LY
		{
			get
			{
				return _dON_VI_QUAN_LY;
			}
			set
			{
				SqlString dON_VI_QUAN_LYTmp = (SqlString)value;
				if(dON_VI_QUAN_LYTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("DON_VI_QUAN_LY", "DON_VI_QUAN_LY can't be NULL");
				}
				_dON_VI_QUAN_LY = value;
			}
		}


		public SqlString GHI_CHU
		{
			get
			{
				return _gHI_CHU;
			}
			set
			{
				SqlString gHI_CHUTmp = (SqlString)value;
				if(gHI_CHUTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GHI_CHU", "GHI_CHU can't be NULL");
				}
				_gHI_CHU = value;
			}
		}


		public SqlDecimal ID_TRANG_THAI_HOP_DONG
		{
			get
			{
				return _iD_TRANG_THAI_HOP_DONG;
			}
			set
			{
				SqlDecimal iD_TRANG_THAI_HOP_DONGTmp = (SqlDecimal)value;
				if(iD_TRANG_THAI_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_TRANG_THAI_HOP_DONG", "ID_TRANG_THAI_HOP_DONG can't be NULL");
				}
				_iD_TRANG_THAI_HOP_DONG = value;
			}
		}


		public SqlString TRANG_THAI_HOP_DONG
		{
			get
			{
				return _tRANG_THAI_HOP_DONG;
			}
			set
			{
				SqlString tRANG_THAI_HOP_DONGTmp = (SqlString)value;
				if(tRANG_THAI_HOP_DONGTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("TRANG_THAI_HOP_DONG", "TRANG_THAI_HOP_DONG can't be NULL");
				}
				_tRANG_THAI_HOP_DONG = value;
			}
		}


		public SqlDecimal ID_DON_VI_THANH_TOAN
		{
			get
			{
				return _iD_DON_VI_THANH_TOAN;
			}
			set
			{
				SqlDecimal iD_DON_VI_THANH_TOANTmp = (SqlDecimal)value;
				if(iD_DON_VI_THANH_TOANTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_DON_VI_THANH_TOAN", "ID_DON_VI_THANH_TOAN can't be NULL");
				}
				_iD_DON_VI_THANH_TOAN = value;
			}
		}


		public SqlString DON_VI_THANH_TOAN
		{
			get
			{
				return _dON_VI_THANH_TOAN;
			}
			set
			{
				SqlString dON_VI_THANH_TOANTmp = (SqlString)value;
				if(dON_VI_THANH_TOANTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("DON_VI_THANH_TOAN", "DON_VI_THANH_TOAN can't be NULL");
				}
				_dON_VI_THANH_TOAN = value;
			}
		}


		public SqlDecimal THUE_SUAT
		{
			get
			{
				return _tHUE_SUAT;
			}
			set
			{
				SqlDecimal tHUE_SUATTmp = (SqlDecimal)value;
				if(tHUE_SUATTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("THUE_SUAT", "THUE_SUAT can't be NULL");
				}
				_tHUE_SUAT = value;
			}
		}


		public SqlDecimal ID_MON1
		{
			get
			{
				return _iD_MON1;
			}
			set
			{
				SqlDecimal iD_MON1Tmp = (SqlDecimal)value;
				if(iD_MON1Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON1", "ID_MON1 can't be NULL");
				}
				_iD_MON1 = value;
			}
		}


		public SqlString FIRST_MON
		{
			get
			{
				return _fIRST_MON;
			}
			set
			{
				SqlString fIRST_MONTmp = (SqlString)value;
				if(fIRST_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("FIRST_MON", "FIRST_MON can't be NULL");
				}
				_fIRST_MON = value;
			}
		}


		public SqlDecimal ID_MON2
		{
			get
			{
				return _iD_MON2;
			}
			set
			{
				SqlDecimal iD_MON2Tmp = (SqlDecimal)value;
				if(iD_MON2Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON2", "ID_MON2 can't be NULL");
				}
				_iD_MON2 = value;
			}
		}


		public SqlString SEC_MON
		{
			get
			{
				return _sEC_MON;
			}
			set
			{
				SqlString sEC_MONTmp = (SqlString)value;
				if(sEC_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("SEC_MON", "SEC_MON can't be NULL");
				}
				_sEC_MON = value;
			}
		}


		public SqlDecimal ID_MON3
		{
			get
			{
				return _iD_MON3;
			}
			set
			{
				SqlDecimal iD_MON3Tmp = (SqlDecimal)value;
				if(iD_MON3Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON3", "ID_MON3 can't be NULL");
				}
				_iD_MON3 = value;
			}
		}


		public SqlString THIR_MON
		{
			get
			{
				return _tHIR_MON;
			}
			set
			{
				SqlString tHIR_MONTmp = (SqlString)value;
				if(tHIR_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("THIR_MON", "THIR_MON can't be NULL");
				}
				_tHIR_MON = value;
			}
		}


		public SqlDecimal ID_MON4
		{
			get
			{
				return _iD_MON4;
			}
			set
			{
				SqlDecimal iD_MON4Tmp = (SqlDecimal)value;
				if(iD_MON4Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON4", "ID_MON4 can't be NULL");
				}
				_iD_MON4 = value;
			}
		}


		public SqlString FOURTH_MON
		{
			get
			{
				return _fOURTH_MON;
			}
			set
			{
				SqlString fOURTH_MONTmp = (SqlString)value;
				if(fOURTH_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("FOURTH_MON", "FOURTH_MON can't be NULL");
				}
				_fOURTH_MON = value;
			}
		}


		public SqlDecimal ID_MON5
		{
			get
			{
				return _iD_MON5;
			}
			set
			{
				SqlDecimal iD_MON5Tmp = (SqlDecimal)value;
				if(iD_MON5Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON5", "ID_MON5 can't be NULL");
				}
				_iD_MON5 = value;
			}
		}


		public SqlString FITH_MON
		{
			get
			{
				return _fITH_MON;
			}
			set
			{
				SqlString fITH_MONTmp = (SqlString)value;
				if(fITH_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("FITH_MON", "FITH_MON can't be NULL");
				}
				_fITH_MON = value;
			}
		}


		public SqlDecimal ID_MON6
		{
			get
			{
				return _iD_MON6;
			}
			set
			{
				SqlDecimal iD_MON6Tmp = (SqlDecimal)value;
				if(iD_MON6Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID_MON6", "ID_MON6 can't be NULL");
				}
				_iD_MON6 = value;
			}
		}


		public SqlString SIXTH_MON
		{
			get
			{
				return _sIXTH_MON;
			}
			set
			{
				SqlString sIXTH_MONTmp = (SqlString)value;
				if(sIXTH_MONTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("SIXTH_MON", "SIXTH_MON can't be NULL");
				}
				_sIXTH_MON = value;
			}
		}


		public SqlString HOC_LIEU_YN
		{
			get
			{
				return _hOC_LIEU_YN;
			}
			set
			{
				SqlString hOC_LIEU_YNTmp = (SqlString)value;
				if(hOC_LIEU_YNTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("HOC_LIEU_YN", "HOC_LIEU_YN can't be NULL");
				}
				_hOC_LIEU_YN = value;
			}
		}


		public SqlString VAN_HANH_YN
		{
			get
			{
				return _vAN_HANH_YN;
			}
			set
			{
				SqlString vAN_HANH_YNTmp = (SqlString)value;
				if(vAN_HANH_YNTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("VAN_HANH_YN", "VAN_HANH_YN can't be NULL");
				}
				_vAN_HANH_YN = value;
			}
		}


		public SqlString MA_PO_PHU_TRACH
		{
			get
			{
				return _mA_PO_PHU_TRACH;
			}
			set
			{
				SqlString mA_PO_PHU_TRACHTmp = (SqlString)value;
				if(mA_PO_PHU_TRACHTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("MA_PO_PHU_TRACH", "MA_PO_PHU_TRACH can't be NULL");
				}
				_mA_PO_PHU_TRACH = value;
			}
		}


		public SqlString GHI_CHU2
		{
			get
			{
				return _gHI_CHU2;
			}
			set
			{
				SqlString gHI_CHU2Tmp = (SqlString)value;
				if(gHI_CHU2Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GHI_CHU2", "GHI_CHU2 can't be NULL");
				}
				_gHI_CHU2 = value;
			}
		}


		public SqlString GHI_CHU3
		{
			get
			{
				return _gHI_CHU3;
			}
			set
			{
				SqlString gHI_CHU3Tmp = (SqlString)value;
				if(gHI_CHU3Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GHI_CHU3", "GHI_CHU3 can't be NULL");
				}
				_gHI_CHU3 = value;
			}
		}


		public SqlString GHI_CHU4
		{
			get
			{
				return _gHI_CHU4;
			}
			set
			{
				SqlString gHI_CHU4Tmp = (SqlString)value;
				if(gHI_CHU4Tmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("GHI_CHU4", "GHI_CHU4 can't be NULL");
				}
				_gHI_CHU4 = value;
			}
		}


		public SqlString CO_SO_HD_YN
		{
			get
			{
				return _cO_SO_HD_YN;
			}
			set
			{
				SqlString cO_SO_HD_YNTmp = (SqlString)value;
				if(cO_SO_HD_YNTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("CO_SO_HD_YN", "CO_SO_HD_YN can't be NULL");
				}
				_cO_SO_HD_YN = value;
			}
		}
		#endregion
	}
}
