///************************************************
/// Generated by: ninhvh
/// Date: 27/06/2012 11:22:38
/// Goal: Create User Service Class for TBL_GD_THANH_TOAN
///************************************************
/// <summary>
/// Create User Service Class for TBL_GD_THANH_TOAN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS
{

    public class US_TBL_GD_THANH_TOAN : US_Object
    {
        private const string c_TableName = "TBL_GD_THANH_TOAN";
        #region "Public Properties"
        public string strSO_PHIEU_THANH_TOAN
        {
            get
            {
                return CNull.RowNVLString(pm_objDR, "SO_PHIEU_THANH_TOAN", IPConstants.c_DefaultString);
            }
            set
            {
                pm_objDR["SO_PHIEU_THANH_TOAN"] = value;
            }
        }

        public bool IsSO_PHIEU_THANH_TOANNull()
        {
            return pm_objDR.IsNull("SO_PHIEU_THANH_TOAN");
        }

        public void SetSO_PHIEU_THANH_TOANNull()
        {
            pm_objDR["SO_PHIEU_THANH_TOAN"] = System.Convert.DBNull;
        }

        public decimal dcID_GIANG_VIEN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "ID_GIANG_VIEN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["ID_GIANG_VIEN"] = value;
            }
        }

        public bool IsID_GIANG_VIENNull()
        {
            return pm_objDR.IsNull("ID_GIANG_VIEN");
        }

        public void SetID_GIANG_VIENNull()
        {
            pm_objDR["ID_GIANG_VIEN"] = System.Convert.DBNull;
        }

        public decimal dcTONG_TIEN_THANH_TOAN
        {
            get
            {
                return CNull.RowNVLDecimal(pm_objDR, "TONG_TIEN_THANH_TOAN", IPConstants.c_DefaultDecimal);
            }
            set
            {
                pm_objDR["TONG_TIEN_THANH_TOAN"] = value;
            }
        }

        public bool IsTONG_TIEN_THANH_TOANNull()
        {
            return pm_objDR.IsNull("TONG_TIEN_THANH_TOAN");
        }

        public void SetTONG_TIEN_THANH_TOANNull()
        {
            pm_objDR["TONG_TIEN_THANH_TOAN"] = System.Convert.DBNull;
        }

        #endregion
        #region "Init Functions"
        public US_TBL_GD_THANH_TOAN()
        {
            pm_objDS = new DS_TBL_GD_THANH_TOAN();
            pm_strTableName = c_TableName;
            pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
        }

        public US_TBL_GD_THANH_TOAN(DataRow i_objDR)
            : this()
        {
            this.DataRow2Me(i_objDR);
        }

        public US_TBL_GD_THANH_TOAN(decimal i_dbID)
        {
            pm_objDS = new DS_TBL_GD_THANH_TOAN();
            pm_strTableName = c_TableName;
            IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
            v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
            SqlCommand v_cmdSQL;
            v_cmdSQL = v_objMkCmd.getSelectCmd();
            this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
            pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
        }
        #endregion
    }
}
